module.exports = {
  apps: [
    {
      name: "sales-api",
      script: "npm",
      args: "start",
      cwd: "/var/www/ai-agent-saas/server",
      instances: "max",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        API_PORT: 4400,
      },
      env_production: {
        NODE_ENV: "production",
        API_PORT: 4400,
      },
      error_file: "./logs/err.log",
      out_file: "./logs/out.log",
      log_file: "./logs/combined.log",
      time: true,
      max_memory_restart: "500M",
      restart_delay: 4000,
      max_restarts: 10,
      exp_backoff_restart_delay: 100,
      watch: false,
      ignore_watch: ["node_modules", "dist", "logs"],
    },
    {
      name: "sales-worker",
      script: "npm",
      args: "run worker",
      cwd: "/var/www/ai-agent-saas/server",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        API_PORT: 4400,
      },
      error_file: "./logs/worker-err.log",
      out_file: "./logs/worker-out.log",
      log_file: "./logs/worker-combined.log",
      time: true,
      max_memory_restart: "500M",
      restart_delay: 4000,
      max_restarts: 10,
      exp_backoff_restart_delay: 100,
      watch: false,
      ignore_watch: ["node_modules", "dist", "logs"],
    },
  ],
};
