ALTER TYPE "CredentialProvider" ADD VALUE IF NOT EXISTS 'GOOGLE_CUSTOM_SEARCH';
ALTER TYPE "CredentialProvider" ADD VALUE IF NOT EXISTS 'SERPER';
ALTER TYPE "CredentialProvider" ADD VALUE IF NOT EXISTS 'BRAVE_SEARCH';
ALTER TYPE "CredentialProvider" ADD VALUE IF NOT EXISTS 'FIRECRAWL';
ALTER TYPE "CredentialProvider" ADD VALUE IF NOT EXISTS 'HUNTER';
ALTER TYPE "CredentialProvider" ADD VALUE IF NOT EXISTS 'CLEARBIT';
ALTER TYPE "CredentialProvider" ADD VALUE IF NOT EXISTS 'HUBSPOT';
