'use client';

import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, Sparkles, Link2, RefreshCw, Send, Package, TrendingUp } from 'lucide-react';
import { SectionShell } from '@/components/section-shell';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { apiRequest } from '@/lib/api';

type Product = { id: string; name: string; description: string; audience: string; claims: string; voice: string; website: string; callToAction: string; growthPlan?: Plan | null };
type Account = { id: string; name: string; platform: string; active: boolean; checkedAt: string; externalId: string };
type Evidence = { title: string; url: string; date: string; summary: string };
type Post = { id: string; caption: string; imageUrl: string | null; creativeBrief: string; rationale: string; status: string; scheduledAt: string | null; publishedAt: string | null; permalink: string | null; providerId: string | null; failureReason: string | null; evidence: Evidence[] | null; account: Account; product: Product; metrics: { likes: number | null; comments: number | null; checkedAt: string } | null };
type Plan = { strategy: string; measurement: string; ideas: { day: number; goal: string; angle: string; reasonToFollow: string; callToAction: string }[] };
const blankProduct = { name: '', description: '', audience: '', claims: '', voice: 'Helpful, specific, warm and professional', website: '', callToAction: 'Book a product demonstration' };
const box = 'rounded-2xl border border-violet-100 bg-white p-5';
const textarea = 'mt-1 min-h-24 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm focus:outline-violet-500';
const label = 'block text-sm font-semibold text-slate-700';

export default function SocialPage() {
  const [tab, setTab] = useState('Studio');
  const [products, setProducts] = useState<Product[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [posts, setPosts] = useState<Post[]>([]);
  const [productId, setProductId] = useState('');
  const [accountId, setAccountId] = useState('');
  const [productForm, setProductForm] = useState(blankProduct);
  const [editingProduct, setEditingProduct] = useState('');
  const [angle, setAngle] = useState('Explain one customer problem and demonstrate how our product helps.');
  const [evidence, setEvidence] = useState<Evidence[]>([]);
  const [source, setSource] = useState<Evidence>({ title: '', url: '', date: '', summary: '' });
  const [researchQuery, setResearchQuery] = useState('');
  const [postId, setPostId] = useState('');
  const [caption, setCaption] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [scheduledAt, setScheduledAt] = useState('');
  const [pageId, setPageId] = useState('');
  const [token, setToken] = useState('');
  const [oauthAvailable, setOauthAvailable] = useState(false);
  const [plan, setPlan] = useState<Plan | null>(null);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const selectedPost = posts.find(post => post.id === postId);
  const product = products.find(item => item.id === productId);
  useEffect(() => { setPlan(product?.growthPlan ?? null); }, [product]);
  const activeAccounts = accounts.filter(account => account.active);
  const load = useCallback(async () => {
    const result = await apiRequest<{ products: Product[]; accounts: Account[]; posts: Post[]; oauthAvailable: boolean }>('/social');
    setProducts(result.products); setAccounts(result.accounts); setPosts(result.posts); setOauthAvailable(result.oauthAvailable);
    setProductId(current => current || result.products[0]?.id || ''); setAccountId(current => current || result.accounts.find(a => a.active)?.id || '');
  }, []);
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.has('connected')) setNotice('Meta accounts connected. Choose an account in the studio.'); if (params.has('connection_error')) setError(params.get('connection_error')!); void load().catch(e => setError(e.message)).finally(() => setLoading(false)); }, [load]);
  useEffect(() => { if (!posts.some(p => ['SCHEDULED', 'PUBLISHING'].includes(p.status))) return; const timer = setInterval(() => { void load().catch(e => setError(e.message)); }, 10000); return () => clearInterval(timer); }, [posts, load]);
  async function act(fn: () => Promise<void>) { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to complete this action'); } finally { setBusy(false); } }
  function selectPost(post: Post) { setPostId(post.id); setCaption(post.caption); setImageUrl(post.imageUrl ?? ''); setProductId(post.product.id); setAccountId(post.account.id); setTab('Studio'); }
  async function saveDraft() {
    if (postId) await apiRequest(`/social/posts/${postId}`, { method: 'PATCH', body: JSON.stringify({ caption, imageUrl: imageUrl || null }) });
    else { const result = await apiRequest<{ post: Post }>('/social/posts', { method: 'POST', body: JSON.stringify({ productId, accountId, caption, imageUrl: imageUrl || null }) }); setPostId(result.post.id); }
    await load(); setNotice('Draft saved. Review and approve when ready.');
  }
  const editable = !selectedPost || ['DRAFT', 'FAILED', 'CANCELLED'].includes(selectedPost.status);
  return <SectionShell active="/social" eyebrow="Content that starts conversations" title="Social Media" description="Turn your product knowledge into useful posts, relevant followers and sales enquiries.">
    {error && <p role="alert" className="mb-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
    {notice && <p role="status" className="mb-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}
    <nav aria-label="Social Media sections" className="mb-5 flex flex-wrap gap-2">{['Studio', 'Products', 'Accounts', 'Calendar', 'Results', 'Growth'].map(item => <Button key={item} variant={tab === item ? 'default' : 'outline'} onClick={() => setTab(item)}>{item}</Button>)}<Button variant="ghost" disabled={busy} onClick={() => void act(load)} aria-label="Refresh social data"><RefreshCw className="size-4" /></Button></nav>
    {loading ? <p>Loading your social workspace…</p> : <>
    {tab === 'Products' && <div className="grid gap-5 lg:grid-cols-2"><form className={box} onSubmit={e => { e.preventDefault(); void act(async () => { await apiRequest(`/social/products${editingProduct ? `/${editingProduct}` : ''}`, { method: editingProduct ? 'PUT' : 'POST', body: JSON.stringify(productForm) }); await load(); setEditingProduct(''); setProductForm(blankProduct); setNotice('Product profile saved.'); }); }}><h2 className="mb-4 text-lg font-bold">{editingProduct ? 'Edit product' : 'Add a product'}</h2>{(['name', 'description', 'audience', 'claims', 'voice', 'website', 'callToAction'] as const).map(key => <label key={key} className={`${label} mb-3`}>{({ name: 'Product name', description: 'What it does', audience: 'Who it helps', claims: 'Approved features and claims', voice: 'Brand voice', website: 'Website / landing page', callToAction: 'Desired next step' })[key]}{['name', 'website'].includes(key) ? <Input required type={key === 'website' ? 'url' : 'text'} value={productForm[key]} onChange={e => setProductForm({ ...productForm, [key]: e.target.value })} /> : <textarea required className={textarea} value={productForm[key]} onChange={e => setProductForm({ ...productForm, [key]: e.target.value })} />}</label>)}<Button disabled={busy}><Package className="size-4" />Save product</Button></form><div className="space-y-3">{products.map(p => <article key={p.id} className={box}><h3 className="font-bold">{p.name}</h3><p className="my-2 text-sm text-slate-600">{p.description}</p><p className="mb-3 text-sm">Audience: {p.audience}</p><Button variant="outline" onClick={() => { setEditingProduct(p.id); setProductForm(p); }}>Edit profile</Button></article>)}{!products.length && <p className={box}>Start with one real product. Its approved facts will guide every draft.</p>}</div></div>}
    {tab === 'Accounts' && <div className="grid gap-5 lg:grid-cols-2"><section className={box}><h2 className="text-lg font-bold">Connect Facebook & Instagram</h2><p className="my-3 text-sm text-slate-600">Connect Pages you manage and their linked professional Instagram accounts. Meta must grant publishing access. Your tokens stay encrypted on the server.</p><Button disabled={busy || !oauthAvailable} onClick={() => void act(async () => { const result = await apiRequest<{ url: string }>('/social/oauth/start', { method: 'POST' }); window.location.assign(result.url); })}><Link2 className="size-4" />Connect with Meta</Button>{!oauthAvailable && <p className="mt-2 text-sm text-amber-700">Meta login needs server setup. You can connect your own Page access token below.</p>}<form className="mt-6 space-y-3" onSubmit={e => { e.preventDefault(); void act(async () => { await apiRequest('/social/accounts', { method: 'POST', body: JSON.stringify({ pageId, token }) }); setToken(''); await load(); setNotice('Page and linked Instagram account connected.'); }); }}><label className={label}>Facebook Page ID<Input required value={pageId} onChange={e => setPageId(e.target.value)} /></label><label className={label}>Page access token<Input required type="password" autoComplete="off" value={token} onChange={e => setToken(e.target.value)} /></label><Button disabled={busy}>Validate & connect</Button></form></section><div className="space-y-3">{accounts.map(a => <article className={box} key={a.id}><h3 className="font-bold">{a.name}</h3><p className="my-2 text-sm">{a.platform} · {a.active ? 'Connected' : 'Disconnected'}</p><p className="mb-3 text-xs text-slate-500">Last checked {new Date(a.checkedAt).toLocaleString()}</p><div className="flex gap-2"><Button disabled={busy} variant="outline" onClick={() => void act(async () => { await apiRequest(`/social/accounts/${a.id}/check`, { method: 'POST' }); await load(); setNotice('Token can access the account. Publishing permissions are checked by Meta on submission.'); })}>Check connection</Button>{a.active && <Button disabled={busy} variant="outline" onClick={() => void act(async () => { await apiRequest(`/social/accounts/${a.id}`, { method: 'DELETE' }); await load(); setNotice('Account disconnected and its scheduled posts cancelled.'); })}>Disconnect</Button>}</div></article>)}</div></div>}
    {tab === 'Studio' && <div className="grid gap-5 xl:grid-cols-[1fr_1fr]"><section className={`${box} space-y-4`}><h2 className="text-lg font-bold">Create a useful post</h2>{!products.length && <Button onClick={() => setTab('Products')}>Add your first product</Button>}{!activeAccounts.length && <Button onClick={() => setTab('Accounts')}>Connect a publishing account</Button>}<label className={label}>Product<select className="mt-1 w-full rounded-xl border p-3" value={productId} disabled={Boolean(postId)} onChange={e => setProductId(e.target.value)}><option value="">Choose product</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className={label}>Publish to<select className="mt-1 w-full rounded-xl border p-3" value={accountId} disabled={Boolean(postId)} onChange={e => setAccountId(e.target.value)}><option value="">Choose account</option>{activeAccounts.map(a => <option key={a.id} value={a.id}>{a.platform} · {a.name}</option>)}</select></label><label className={label}>Post idea or customer question<textarea className={textarea} value={angle} onChange={e => setAngle(e.target.value)} /></label>
      <details className="rounded-xl bg-violet-50 p-3"><summary className="cursor-pointer text-sm font-semibold">Add timely research ({evidence.length} sources)</summary><p className="my-2 text-sm">Recent news is a source of ideas, not proof that a topic is trending.</p><Input aria-label="Research query" placeholder="Industry topic to research" value={researchQuery} onChange={e => setResearchQuery(e.target.value)} /><Button className="my-2" disabled={busy || !researchQuery} variant="outline" onClick={() => void act(async () => { const result = await apiRequest<{ evidence: Evidence[] }>('/social/research', { method: 'POST', body: JSON.stringify({ query: researchQuery }) }); setEvidence(result.evidence); setNotice('Sources loaded. Review them before generating.'); })}>Research current topics</Button>{(['title', 'url', 'date', 'summary'] as const).map(key => <label key={key} className="my-2 block text-sm">{key}<Input value={source[key]} onChange={e => setSource({ ...source, [key]: e.target.value })} /></label>)}<Button variant="outline" disabled={!source.url || !source.title || !source.date || evidence.length >= 10} onClick={() => { setEvidence([...evidence, source]); setSource({ title: '', url: '', date: '', summary: '' }); }}>Add source note</Button>{evidence.map((s, i) => <div key={i} className="mt-2 text-sm"><a className="text-violet-700 underline" href={s.url} target="_blank" rel="noreferrer">{s.title}</a> · {s.date}<button className="ml-2" onClick={() => setEvidence(evidence.filter((_, index) => index !== i))}>Remove</button></div>)}</details>
      <Button disabled={busy || !productId || !accountId} onClick={() => void act(async () => { const result = await apiRequest<{ post: Post }>('/social/generate', { method: 'POST', body: JSON.stringify({ productId, accountId, angle, evidence }) }); await load(); setPostId(result.post.id); setCaption(result.post.caption); setImageUrl(''); setNotice('AI draft created. Review the copy and add your image before approving.'); })}><Sparkles className="size-4" />{busy ? 'Working…' : 'Generate AI draft'}</Button><Button className="ml-2" variant="outline" onClick={() => { setPostId(''); setCaption(''); setImageUrl(''); }}>New manual draft</Button></section>
      <section className={`${box} space-y-4`}><h2 className="text-lg font-bold">Preview & approve</h2>{selectedPost && <p className="text-sm font-semibold text-violet-700">{selectedPost.status === 'UNCERTAIN' ? 'Needs verification' : selectedPost.status}</p>}<label className={label}>Caption<textarea className={`${textarea} min-h-52`} disabled={!editable} value={caption} onChange={e => setCaption(e.target.value)} /></label><p className="text-xs text-slate-500">{caption.length} characters · Instagram captions allow up to 2,200.</p><label className={label}>Public image URL (JPEG for Instagram)<Input type="url" disabled={!editable} value={imageUrl} onChange={e => setImageUrl(e.target.value)} placeholder="https://your-site.com/product.jpg" /></label>{imageUrl.startsWith('https://') && <img alt="Post image preview" src={imageUrl} className="max-h-72 w-full rounded-xl object-contain" />}{selectedPost?.creativeBrief && <p className="rounded-xl bg-violet-50 p-3 text-sm"><strong>Creative brief: </strong>{selectedPost.creativeBrief}</p>}{selectedPost?.rationale && <p className="text-sm text-slate-600">{selectedPost.rationale}</p>}{selectedPost?.failureReason && <p className="text-sm text-rose-700">{selectedPost.failureReason}</p>}<Button variant="outline" disabled={busy || !editable || !caption || !productId || !accountId} onClick={() => void act(saveDraft)}>Save draft</Button><label className={label}>Schedule in your local time (leave empty for now)<Input type="datetime-local" value={scheduledAt} onChange={e => setScheduledAt(e.target.value)} /></label><Button disabled={busy || !selectedPost || !editable || caption !== selectedPost.caption || imageUrl !== (selectedPost.imageUrl ?? '')} onClick={() => void act(async () => { await apiRequest(`/social/posts/${postId}/schedule`, { method: 'POST', body: JSON.stringify({ scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : new Date().toISOString() }) }); await load(); setNotice('Approved and scheduled. The publishing worker checks due posts every 15 seconds.'); })}><Send className="size-4" />{scheduledAt ? 'Approve & schedule' : 'Approve & publish now'}</Button><p className="text-xs text-slate-500">Save edits before approval. Approval submits this post to the selected social account.</p></section></div>}
    {(tab === 'Calendar' || tab === 'Results') && <section className={box}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">{tab === 'Calendar' ? 'Publishing calendar' : 'Publishing results'}</h2><select aria-label="Filter by status" className="rounded-xl border p-2" value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>{['ALL', 'DRAFT', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'UNCERTAIN', 'CANCELLED'].map(s => <option key={s}>{s}</option>)}</select></div><p className="mb-4 text-sm text-slate-600">Latest 200 posts. Published requires a Meta post ID. Engagement is not a count of sales or new followers.</p><div className="space-y-3">{posts.filter(p => statusFilter === 'ALL' || p.status === statusFilter).sort((a, b) => (a.scheduledAt ?? '').localeCompare(b.scheduledAt ?? '')).map(p => <article className="rounded-xl border p-4" key={p.id}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{p.product.name} · {p.account.platform}</h3><span className="text-sm font-semibold">{p.status === 'UNCERTAIN' ? 'Needs verification' : p.status}</span></div><p className="my-2 line-clamp-3 whitespace-pre-wrap text-sm text-slate-600">{p.caption}</p><p className="mb-3 text-sm">{p.publishedAt ? `Published ${new Date(p.publishedAt).toLocaleString()}` : p.scheduledAt ? `Scheduled ${new Date(p.scheduledAt).toLocaleString()}` : 'Unscheduled draft'}</p>{p.failureReason && <p className="my-2 text-sm text-rose-700">{p.failureReason}</p>}{p.metrics && <p className="my-2 text-sm">Likes: {p.metrics.likes ?? 'Unavailable'} · Comments: {p.metrics.comments ?? 'Unavailable'} · Checked {new Date(p.metrics.checkedAt).toLocaleString()}</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => selectPost(p)}>Review post</Button>{['DRAFT', 'SCHEDULED', 'FAILED'].includes(p.status) && <Button disabled={busy} variant="outline" onClick={() => void act(async () => { await apiRequest(`/social/posts/${p.id}/cancel`, { method: 'POST' }); await load(); })}>Cancel</Button>}{p.permalink && <a href={p.permalink} target="_blank" rel="noreferrer" className="rounded-xl border px-3 py-2 text-sm text-violet-700">View published post</a>}{p.status === 'PUBLISHED' && <Button disabled={busy} variant="outline" onClick={() => void act(async () => { await apiRequest(`/social/posts/${p.id}/metrics`, { method: 'POST' }); await load(); })}>Refresh engagement</Button>}</div></article>)}{!posts.length && <p>No posts yet. Create your first draft in the studio.</p>}</div></section>}
    {tab === 'Growth' && <section className={`${box} space-y-4`}><h2 className="flex items-center gap-2 text-lg font-bold"><TrendingUp className="size-5" />Audience growth plan</h2><p className="text-sm text-slate-600">Build a reason to follow: useful education, product demonstrations, customer questions, and occasional offers. The agent uses available engagement data to suggest experiments.</p><label className={label}>Product<select className="ml-3 rounded-xl border p-2" value={productId} onChange={e => { setProductId(e.target.value); setPlan(null); }}>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Button disabled={busy || !product} onClick={() => void act(async () => { const result = await apiRequest<{ plan: Plan }>('/social/growth-plan', { method: 'POST', body: JSON.stringify({ productId }) }); setPlan(result.plan); })}><Sparkles className="size-4" />{busy ? 'Planning…' : 'Create 7-day growth plan'}</Button>{plan && <><p className="whitespace-pre-wrap text-sm">{plan.strategy}</p><div className="grid gap-3 md:grid-cols-2">{plan.ideas.map((idea, i) => <article className="rounded-xl border bg-violet-50/40 p-4" key={i}><h3 className="font-semibold">Day {idea.day} · {idea.goal.toLowerCase()}</h3><p className="my-2 text-sm">{idea.angle}</p><p className="mb-2 text-sm text-slate-600">Reason to follow: {idea.reasonToFollow}</p><Button variant="outline" onClick={() => { setAngle(`${idea.angle}\nCall to action: ${idea.callToAction}`); setPostId(''); setCaption(''); setImageUrl(''); setTab('Studio'); }}>Use this idea</Button></article>)}</div><p className="rounded-xl bg-emerald-50 p-4 text-sm">Measure: {plan.measurement}</p></>}</section>}
    </>}
  </SectionShell>;
}
